### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-IsaGarabana#1]
Really cool job @IsaGarabana !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Use return to transfer values between functions (from called function to caller code). (Here you can use return instead of a global variable: <https://github.com/Adalab/modulo-2-evaluacion-intermedia-IsaGarabana/blob/9b3146bf01a20443a987e81fd59a8489586b24ea/js/main.js#L38> ).
- [x] The switch sentence is intended for evaluate values of a variable. You have to put the name of the variable within the parentheses of the switch and each case sentence has a unique value. It will compare the variable content with its value. You have to combine if with switch sentences to accomplish the computer and the user selection comparation.
- [x] Use three counter variables: one for user wins, other for computer wins and another for total rounds played.
- [x] Increment the round counter always the user clicks on "Jugar" button.
- [x] Watch out for constant names used to save DOM references... Do we want to use the DOM reference or that DOM element content (innerHTML/value)?

### JavaScript: advanced

- [x] Check if the round counter has reached the limit of rounds.
- [x] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Add a reset button that cleans the select, the counter and writes the initial feedback
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by igarridomorillas** [comment]
Perfect!
